basePath: /
definitions:
  main.Pokemon:
    properties:
      image:
        type: string
      number:
        type: string
    type: object
host: localhost:80
info:
  contact:
    name: LmarDark
  description: Esta API serve para listar Pokémons
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: API de Pokémons
  version: "1.0"
paths:
  /pokemons:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/main.Pokemon'
            type: object
      summary: Lista todos os pokémons
swagger: "2.0"
